In [4]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribución de las variables
# ------------------------------------------------------------------------------
#import scipy.stats as stats
from scipy.stats import shapiro, poisson, chisquare, expon, kstest
from scipy import stats

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

1- Evalúa si las siguientes afirmaciones corresponden a una distribución exponencial o poisson:

¿El tiempo que transcurre entre la llegada de autobuses a una parada sigue una distribución exponencial o de Poisson?

*Distribución exponencial*

¿El número de errores en un artículo de noticias sigue una distribución exponencial o de Poisson?

*Distribución de Poisson*

¿El tiempo que transcurre entre la llegada de solicitudes de servicio en un restaurante sigue una distribución exponencial o de Poisson?

*Distribución exponencial*

¿El número de accidentes de tráfico en una hora en una ciudad sigue una distribución exponencial o de Poisson?

*Distribución de Poisson*

¿El tiempo entre llegadas de llamadas telefónicas a una central de emergencias sigue una distribución exponencial o de Poisson?

*Distribución exponencial*

¿El número de clientes que ingresan a una tienda en una hora sigue una distribución exponencial o de Poisson?

*Distribución Poisson*

¿El tiempo entre llegadas de correos electrónicos en una bandeja de entrada sigue una distribución exponencial o de Poisson?

*Distribución exponencial*

¿El número de defectos en una línea de producción por día sigue una distribución exponencial o de Poisson?

*Distribución Poisson*

¿El tiempo que transcurre entre la llegada de taxis en una parada sigue una distribución exponencial o de Poisson?

*Distribución exponencial*

¿El número de errores de ortografía en un libro de texto sigue una distribución exponencial o de Poisson?

*Distribución Poisson*

2- Ejercicios intervalo de confianza. Al igual que en el caso del ejercicio de la clase invertida, piensa un motivo por el que sería interesante calcular estos intervalos de confianza para la extracción de insights.

In [5]:
df = pd.read_csv("files/world_data_full_apply_nulos.csv", index_col = 0 ) 
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa

- Intervalo de Confianza para la Esperanza de Vida   
    - Contexto: Trabajas en una organización de salud global y deseas estimar el intervalo de confianza al 95% para la esperanza de vida promedio de cada continente.   
    - Nota: Cuidado porque puede que os salgan algunos nulos, genera un código para que no salgan nulos en los intervalos de confianza.

In [19]:
for continent, data in df.groupby('continent')['life_expectancy']:
    media_esp = data.mean()
    error_esp = stats.sem(data, nan_policy= "omit")
    nivel_confianza_esp = 0.95
    libertad_esp = len(data) - 1
    valor_critico_esp = stats.t.ppf((1 + nivel_confianza_esp)/2, df=libertad_esp)

    int_inferior = media_esp - valor_critico_esp * error_esp
    int_superior = media_esp + valor_critico_esp * error_esp

    print(f"Intervalo de Confianza para la Esperanza de Vida de {continent.upper()}")
    print(f"Media Muestral: {np.round(media_esp, 2)}")
    print(f"Error Estándar: {np.round(error_esp, 2)}")
    print(f"Nivel de Confianza: {nivel_confianza_esp}")
    print(f"Valor Crítico: {np.round(valor_critico_esp, 2)}")
    print(f"Intervalo de Confianza: ({np.round(int_inferior, 2)}, {np.round(int_superior, 2)})")
    print('---')

Intervalo de Confianza para la Esperanza de Vida de AFRICA
Media Muestral: 63.73
Error Estándar: 0.83
Nivel de Confianza: 0.95
Valor Crítico: 2.01
Intervalo de Confianza: (62.06, 65.39)
---
Intervalo de Confianza para la Esperanza de Vida de ASIA
Media Muestral: 73.78
Error Estándar: 0.72
Nivel de Confianza: 0.95
Valor Crítico: 2.02
Intervalo de Confianza: (72.33, 75.24)
---
Intervalo de Confianza para la Esperanza de Vida de CENTRAL AMERICA
Media Muestral: 74.69
Error Estándar: 0.79
Nivel de Confianza: 0.95
Valor Crítico: 2.09
Intervalo de Confianza: (73.04, 76.34)
---
Intervalo de Confianza para la Esperanza de Vida de EUROPE
Media Muestral: 79.2
Error Estándar: 0.55
Nivel de Confianza: 0.95
Valor Crítico: 2.01
Intervalo de Confianza: (78.09, 80.31)
---
Intervalo de Confianza para la Esperanza de Vida de NORTH AMERICA
Media Muestral: 80.2
Error Estándar: 1.7
Nivel de Confianza: 0.95
Valor Crítico: 12.71
Intervalo de Confianza: (58.6, 101.8)
---
Intervalo de Confianza para la Esperanza de Vida de OCEANIA
Media Muestral: 71.12
Error Estándar: 1.69
Nivel de Confianza: 0.95
Valor Crítico: 2.16
Intervalo de Confianza: (67.47, 74.78)
---
Intervalo de Confianza para la Esperanza de Vida de SOUTH AMERICA
Media Muestral: 74.82
Error Estándar: 0.84
Nivel de Confianza: 0.95
Valor Crítico: 2.18
Intervalo de Confianza: (72.99, 76.64)
---

- Intervalo de Confianza para el PIB   
    - Contexto: Eres una economista y quieres calcular el intervalo de confianza al 90% para el Producto Interno Bruto (PIB) de los continentes.

In [18]:
for continent, data in df.groupby('continent')['gdp']:
    media_gdp = data.mean()
    error_gdp = stats.sem(data, nan_policy= "omit")
    nivel_confianza_gdp = 0.90
    libertad_gdp = len(data) - 1
    valor_critico_gdp = stats.t.ppf((1 + nivel_confianza_gdp)/2, df=libertad_gdp)

    int_inferior = media_gdp - valor_critico_gdp * error_gdp
    int_superior = media_gdp + valor_critico_gdp * error_gdp

    print(f"Intervalo de Confianza para el PIB de {continent.upper()}")
    print(f"Media Muestral: {np.round(media_gdp, 2)}")
    print(f"Error Estándar: {np.round(error_gdp, 2)}")
    print(f"Nivel de Confianza: {nivel_confianza_gdp}")
    print(f"Valor Crítico: {np.round(valor_critico_gdp, 2)}")
    print(f"Intervalo de Confianza: ({np.round(int_inferior, 2)}, {np.round(int_superior, 2)})")
    print('---')

Intervalo de Confianza para el PIB de AFRICA
Media Muestral: 46080559143.87
Error Estándar: 12052560395.91
Nivel de Confianza: 0.9
Valor Crítico: 1.67
Intervalo de Confianza: (25896266980.48, 66264851307.25)
---
Intervalo de Confianza para el PIB de ASIA
Media Muestral: 837195265650.86
Error Estándar: 463167313346.77
Nivel de Confianza: 0.9
Valor Crítico: 1.68
Intervalo de Confianza: (58967662156.24, 1615422869145.49)
---
Intervalo de Confianza para el PIB de CENTRAL AMERICA
Media Muestral: 88479927703.1
Error Estándar: 62002880448.04
Nivel de Confianza: 0.9
Valor Crítico: 1.73
Intervalo de Confianza: (-18731287288.44, 195691142694.64)
---
Intervalo de Confianza para el PIB de EUROPE
Media Muestral: 486748190304.24
Error Estándar: 124182737782.55
Nivel de Confianza: 0.9
Valor Crítico: 1.68
Intervalo de Confianza: (278287544461.41, 695208836147.07)
---
Intervalo de Confianza para el PIB de NORTH AMERICA
Media Muestral: 11582062814760.0
Error Estándar: 9845637185240.0
Nivel de Confianza: 0.9
Valor Crítico: 6.31
Intervalo de Confianza: (-50580843877729.44, 73744969507249.44)
---
Intervalo de Confianza para el PIB de OCEANIA
Media Muestral: 116788555752.29
Error Estándar: 99230087668.92
Nivel de Confianza: 0.9
Valor Crítico: 1.77
Intervalo de Confianza: (-58941320387.31, 292518431891.88)
---
Intervalo de Confianza para el PIB de SOUTH AMERICA
Media Muestral: 298433685548.77
Error Estándar: 136724518484.96
Nivel de Confianza: 0.9
Valor Crítico: 1.78
Intervalo de Confianza: (54751277700.89, 542116093396.64)
---

- Intervalo de Confianza para la Tasa de Natalidad   
    - Contexto: Trabajas en una agencia gubernamental que se ocupa de cuestiones demográficas y deseas determinar el intervalo de confianza al 99% para la tasa de natalidad promedio en Asia.

In [20]:
for continent, data in df.groupby('continent')['birth_rate']:
    if continent == 'Asia':
        media_birth = data.mean()
        error_birth = stats.sem(data, nan_policy= "omit")
        nivel_confianza_birth = 0.99
        libertad_birth = len(data) - 1
        valor_critico_birth = stats.t.ppf((1 + nivel_confianza_birth)/2, df=libertad_birth)

        int_inferior = media_birth - valor_critico_birth * error_birth
        int_superior = media_birth + valor_critico_birth * error_birth

        print(f"Intervalo de Confianza para el PIB de {continent.upper()}")
        print(f"Media Muestral: {np.round(media_birth, 2)}")
        print(f"Error Estándar: {np.round(error_birth, 2)}")
        print(f"Nivel de Confianza: {nivel_confianza_birth}")
        print(f"Valor Crítico: {np.round(valor_critico_birth, 2)}")
        print(f"Intervalo de Confianza: ({np.round(int_inferior, 2)}, {np.round(int_superior, 2)})")
        print('---')

Intervalo de Confianza para el PIB de ASIA
Media Muestral: 18.81
Error Estándar: 0.99
Nivel de Confianza: 0.99
Valor Crítico: 2.69
Intervalo de Confianza: (16.14, 21.48)
---

- Intervalo de Confianza para la Tasa de Desempleo   
    - Contexto: Eres un analista de políticas públicas y deseas calcular el intervalo de confianza al 95% para la tasa de desempleo promedio en los países de Oceanía.

In [22]:
for continent, data in df.groupby('continent')['unemployment_rate']:
    if continent == 'Oceania':
        media = data.mean()
        error = stats.sem(data, nan_policy= "omit")
        nivel_confianza = 0.95
        libertad = len(data) - 1
        valor_critico = stats.t.ppf((1 + nivel_confianza)/2, df=libertad)

        int_inferior = media - valor_critico * error
        int_superior = media + valor_critico * error

        print(f"Intervalo de Confianza para el PIB de {continent.upper()}")
        print(f"Media Muestral: {np.round(media, 2)}")
        print(f"Error Estándar: {np.round(error, 2)}")
        print(f"Nivel de Confianza: {nivel_confianza}")
        print(f"Valor Crítico: {np.round(valor_critico, 2)}")
        print(f"Intervalo de Confianza: ({np.round(int_inferior, 2)}, {np.round(int_superior, 2)})")
        print('---')

Intervalo de Confianza para el PIB de OCEANIA
Media Muestral: 3.79
Error Estándar: 0.87
Nivel de Confianza: 0.95
Valor Crítico: 2.16
Intervalo de Confianza: (1.9, 5.68)
---

- Intervalo de Confianza para la Tasa de Impuestos   
    - Contexto: Trabajas en un ministerio de finanzas y deseas estimar el intervalo de confianza al 90% para la tasa de impuestos promedio en los países de África.

In [24]:
for continent, data in df.groupby('continent')['total_tax_rate']:
    if continent == 'Africa':
        media = data.mean()
        error = stats.sem(data, nan_policy= "omit")
        nivel_confianza = 0.90
        libertad = len(data) - 1
        valor_critico = stats.t.ppf((1 + nivel_confianza)/2, df=libertad)

        int_inferior = media - valor_critico * error
        int_superior = media + valor_critico * error

        print(f"Intervalo de Confianza para el PIB de {continent.upper()}")
        print(f"Media Muestral: {np.round(media, 2)}")
        print(f"Error Estándar: {np.round(error, 2)}")
        print(f"Nivel de Confianza: {nivel_confianza}")
        print(f"Valor Crítico: {np.round(valor_critico, 2)}")
        print(f"Intervalo de Confianza: ({np.round(int_inferior, 2)}, {np.round(int_superior, 2)})")
        print('---')

Intervalo de Confianza para el PIB de AFRICA
Media Muestral: 47.77
Error Estándar: 4.04
Nivel de Confianza: 0.9
Valor Crítico: 1.67
Intervalo de Confianza: (41.0, 54.54)
---

3- Ejercicios prueba de hipótesis: Hasta ahora en la lección y en los ejercicios de la clase invertida os hemos propuesto un contexto y unas hipótesis para entender que es la prueba de hipótesis. Ahora es tu turno, tienes que pensar en 2 hipótesis que quieras aceptar o rechazar usando una prueba de hipótesis en base a los datos que tenemos.

In [30]:
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa